baseURL = "https://sorskoot.github.io/sorskoot-website/"
languageCode = "en-us"
title = "Timmy Kokke"
theme = "initio"
paginate = 5

[params]
    name = "Timmy Kokke"
    description = "Web - Games - VR/AR/XR"
    email = "info@timmykokke.com"
    phone = ""
    address = ""
    year = 2018
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = false
    showClients = false

    footerEnableContact = false
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

    comments = true
    share = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[[menu.main]]
    name = "WebXR NL"
    url = "https://webxr.nl"
    weight = 5

[params.disqus]
    site = "sorskoot.disqus.com"

[params.sharethis]
    property = "5b5ce62a4970c900111bbb9b"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/sorskoot"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/sorskoot"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/sorskoot360"
    icon = "fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+sorskoot"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/timmykokke"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/sorskoot"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:info@timmykokke.com"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"
