baseURL = "localhost"
languageCode = "en-us"
title = "Timmy Kokke"
theme = "initio"
paginate = 5
pluralizeListTitles = false

[params]
    name = "Timmy Kokke"
    description = "Web - Games - VR/AR/XR"
    email = "info@timmykokke.com"
    phone = ""
    address = ""
    year = 2018
    background = ""
    favicon = "icons/gt_favicon.png"
    DateForm = "January 2, 2006"
    
    

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = false
    showClients = false
    showAgenda = true

    footerEnableContact = false
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

    comments = true
    share = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[[menu.main]]
    name = "twitch"
    url = "/twitch/"
    weight = 6

[[menu.main]]
    name = "portfolio"
    url = "/portfolio/"
    weight = 7

[[menu.main]]
    name = "WebXR NL"
    url = "https://webxr.nl"
    weight = 10
    target = "_blank"

[params.disqus]
    site = "sorskoot.disqus.com"

[params.sharethis]
    property = "5b5ce62a4970c900111bbb9b"
    custom = true

[params.google.analytics]
    trackerID = "UA-11559922-2"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/sorskoot"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/sorskoot"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/sorskoot360"
    icon = "fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+sorskoot"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/timmykokke"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/sorskoot"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:info@timmykokke.com"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false